-- # Lab Exercises Module 2 - Database Objects
-- From: Joan Casteel. 2015. Oracle 12c: SQL, 3rd Edition.
-- Boston: Course Technology.
-- Lab Exercises - Database Objects
-- To perform the following assignments, refer to the tables in the JustLee
-- Books database.
-- 1. Create a sequence for populating the Customer# column of the CUSTOMERS
-- table. When setting the start and increment values, keep in mind that data
-- already exists in this table. The options should be set to not cycle the
-- values and not cache any values, and no minimum or maximum values should be
-- declared.
