DROP SEQUENCE MY_FIRST_SEQ;
CREATE SEQUENCE MY_FIRST_SEQ START WITH 1 INCREMENT BY 1;
SELECT MY_FIRST_SEQ.NEXTVAL FROM dual;
SELECT MY_FIRST_SEQ.NEXTVAL FROM dual;
SELECT MY_FIRST_SEQ.NEXTVAL FROM dual;
SELECT MY_FIRST_SEQ.CURRVAL FROM dual;